columns: Category,Article,ArticleNumber
owner: CSAnalytics@tripadvisor.com
destination: HelpModuleArticlesViatorSite
url: https://docs.google.com/spreadsheets/d/1FR-5Nxi0hJmgUey_iy7PlMGPfInRo11CsgQi-OB6CLU/edit?usp=sharing
