columns: Category,Article,ArticleNumber
owner: CSAnalytics@tripadvisor.com
destination: HelpModuleArticlesNSP
url: https://docs.google.com/spreadsheets/d/18qQNxpcZ_VMRafTICDdWbzWOUqVu77ZNSIG7R9Z3Xhw/edit?usp=sharing
