columns: Partner,PUID,SubPUID,Email
description: This table contains the list of partners receiving traffic reports, and
  is used a filter for SSRS. It is maintained by the BD team.
PrimaryKeys: PUID
owner: rex-wh-dev@tripadvisor.com, meldredge@tripadvisor.com
destination: PartnerTrafficReport
skipHeader: 'true'
url: https://docs.google.com/spreadsheets/d/17JDIM9d69PEpj41rXmwXuEq84WjqhKm4m6UuO_B-qB8/edit?usp=sharing
