columns: Date,English,Japanese,Chinese,Korean,Indonesian,Thai,Vietnamese,Greek,Portuguese,Russian,Turkish,French,German,Italian,Spanish,Dutch,Polish,SinglePlatform,EnglishRest,FrenchRest,ItalianRest,GermanRest,SpanishRest,PortugueseRest,TAPlus
owner: CSAnalytics@tripadvisor.com
destination: TACSEmailsLocked
url: https://docs.google.com/spreadsheets/d/1Tbia3-gd6_6z4xRJvNREXjewcl5-ZKJdgNhmjRycjjY/edit?usp=sharing
