columns: Date,English,Japanese,Chinese,Korean,Indonesian,Thai,Vietnamese,Greek,Portuguese,Russian,Turkish,French,German,Italian,Spanish,Dutch,Polish,SinglePlatform,EnglishRest,FrenchRest,ItalianRest,GermanRest,SpanishRest,PortugueseRest,TAPlus
destination: TACSEmailsPlan
owner: CSAnalytics@tripadvisor.com
url: https://docs.google.com/spreadsheets/d/1-WsqWI43f6nNWksr7n1Ikhq8OMil3Eb9-dqtMyR40jo/edit?usp=sharing
