columns: Date,English,French,German,Portuguese,Spanish,Italian,Japanese,Mandarin,Total
destination: ViatorEmailsPlan
owner: aturnbull@tripadvisor.com
url: https://docs.google.com/spreadsheets/d/1iRhptTouARXzBvB6Wxrmo1IxsTlqoH-rbY0k7_sBaE4/edit?usp=sharing
