columns: Date,English,French,German,Portuguese,Spanish,Italian,Japanese,Mandarin,Total
destination: ViatorEmailsForecast
owner: CSAnalytics@tripadvisor.com
url: https://docs.google.com/spreadsheets/d/1e0hyaR_WihT2p5YqnJdYdj5_UY8Kqn6HSCjoTBSpTrs/edit?usp=sharing
