columns: Date,English,French,German,Portuguese,Spanish,Italian,Japanese,Mandarin,Total
destination: ViatorEmailsLocked
owner: aturnbull@tripadvisor.com
url: https://docs.google.com/spreadsheets/d/1ZuFtRi18-uaeFVLt48a-2Ga25Z0VRr9e_Kv7xJvm4eU/edit?usp=sharing
