with cte as (
SELECT
    id,
    '' as guid,
    user_id,
    external_user_id as customer_id,
    TIMESTAMP_SECONDS(time) as time,
    cast(TIMESTAMP_SECONDS(time) as DATE) as event_date,
    cast(TIMESTAMP_SECONDS(time) as TIME) as event_hour,
    timezone,
    name,
    app_id,
    platform,
    os_version,
    device_model,
    device_id,
    properties,
    ad_id,
    ad_id_type,
    ad_tracking_enabled,
    '' as product_id,
    0.0 as price,
    '' as currency,
    '' as session_id,
    '' as gender,
    '' as country,
    '' as language,
    '' as sdk_version,
    0.0 as duration,
    0.0 as longitude,
    0.0 as latitude,
    0.0 as altitude,
    0.0 as ll_accuracy,
    0.0 as alt_accuracy,
    '' as source,
    '' as app_group_id,
    null as random_bucket_number,
    null as prev_random_bucket_number,
    `date` as athena_partition,
    'customevent' as event_type
FROM {{project_id}}.{{dataset_id}}.event_type_users_behaviors_customevent
UNION ALL
SELECT
    id,
    '' as guid,
    user_id,
    external_user_id as customer_id,
    TIMESTAMP_SECONDS(time) as time,
    cast(TIMESTAMP_SECONDS(time) as DATE) as event_date,
    cast(TIMESTAMP_SECONDS(time) as TIME) as event_hour,
    timezone,
    '' as name,
    app_id,
    platform,
    os_version,
    device_model,
    device_id,
    '' as properties,
    '' as ad_id,
    '' as ad_id_type,
    false as ad_tracking_enabled,
    '' as product_id,
    0.0 as price,
    '' as currency,
    session_id,
    gender,
    country,
    language,
    sdk_version,
    0.0 as duration,
    0.0 as longitude,
    0.0 as latitude,
    0.0 as altitude,
    0.0 as ll_accuracy,
    0.0 as alt_accuracy,
    '' as source,
    '' as app_group_id,
    null as random_bucket_number,
    null as prev_random_bucket_number,
    `date` as athena_partition,
    'firstsession' as event_type
FROM {{project_id}}.{{dataset_id}}.event_type_users_behaviors_app_firstsession
UNION ALL
SELECT
    id,
    '' as guid,
    user_id,
    external_user_id as customer_id,
    TIMESTAMP_SECONDS(time) as time,
    cast(TIMESTAMP_SECONDS(time) as DATE) as event_date,
    cast(TIMESTAMP_SECONDS(time) as TIME) as event_hour,
    '' as timezone,
    '' as name,
    app_id,
    platform,
    os_version,
    device_model,
    device_id,
    '' as properties,
    '' as ad_id,
    '' as ad_id_type,
    false as ad_tracking_enabled,
    '' as product_id,
    0.0 as price,
    '' as currency,
    session_id,
    '' as gender,
    '' as country,
    '' as language,
    '' as sdk_version,
    0.0 as duration,
    0.0 as longitude,
    0.0 as latitude,
    0.0 as altitude,
    0.0 as ll_accuracy,
    0.0 as alt_accuracy,
    '' as source,
    '' as app_group_id,
    null as random_bucket_number,
    null as prev_random_bucket_number,
    `date` as athena_partition,
    'sessionend' as event_type
FROM {{project_id}}.{{dataset_id}}.event_type_users_behaviors_app_sessionend
UNION ALL
SELECT
    id,
    '' as guid,
    user_id,
    external_user_id as customer_id,
    TIMESTAMP_SECONDS(time) as time,
    cast(TIMESTAMP_SECONDS(time) as DATE) as event_date,
    cast(TIMESTAMP_SECONDS(time) as TIME) as event_hour,
    '' as timezone,
    '' as name,
    app_id,
    platform,
    os_version,
    device_model,
    device_id,
    '' as properties,
    '' as ad_id,
    '' as ad_id_type,
    false as ad_tracking_enabled,
    '' as product_id,
    0.0 as price,
    '' as currency,
    session_id,
    '' as gender,
    '' as country,
    '' as language,
    '' as sdk_version,
    0.0 as duration,
    0.0 as longitude,
    0.0 as latitude,
    0.0 as altitude,
    0.0 as ll_accuracy,
    0.0 as alt_accuracy,
    '' as source,
    '' as app_group_id,
    null as random_bucket_number,
    null as prev_random_bucket_number,
    `date` as athena_partition,
    'sessionstart' as event_type
FROM {{project_id}}.{{dataset_id}}.event_type_users_behaviors_app_sessionstart
UNION ALL
SELECT
    id,
    '' as guid,
    user_id,
    external_user_id as customer_id,
    TIMESTAMP_SECONDS(time) as time,
    cast(TIMESTAMP_SECONDS(time) as DATE) as event_date,
    cast(TIMESTAMP_SECONDS(time) as TIME) as event_hour,
    '' as timezone,
    '' as name,
    app_id,
    platform,
    os_version,
    device_model,
    '' as device_id,
    '' as properties,
    '' as ad_id,
    '' as ad_id_type,
    false as ad_tracking_enabled,
    '' as product_id,
    0.0 as price,
    '' as currency,
    '' as session_id,
    '' as gender,
    '' as country,
    '' as language,
    '' as sdk_version,
    0.0 as duration,
    0.0 as longitude,
    0.0 as latitude,
    0.0 as altitude,
    0.0 as ll_accuracy,
    0.0 as alt_accuracy,
    '' as source,
    '' as app_group_id,
    null as random_bucket_number,
    null as prev_random_bucket_number,
    `date` as athena_partition,
    'newsfeedimpression' as event_type
FROM {{project_id}}.{{dataset_id}}.event_type_users_behaviors_app_newsfeedimpression
)
select * except(row_num) 
from (
    select *,
    row_number() over ( partition by id order by id ) row_num
    from cte) t
where row_num=1;