CREATE TABLE IF NOT EXISTS `{dwh_project_id}.viator_appsflyer.viator_appsflyer_cost_etl_{event}`
(
    app_id STRING,
    media_source STRING,
    date STRING,
    os STRING,
    agency STRING,
    campaign STRING,
    campaign_id STRING,
    adset STRING,
    adset_id STRING,
    ad STRING,
    ad_id STRING,
    channel STRING,
    geo STRING,
    site_id STRING,
    keyword_id STRING,
    keyword_term STRING,
    timezone STRING,
    ad_account STRING,
    currency STRING,
    original_currency STRING,
    campaign_objective STRING,
    cost_model STRING,
    af_cost_model STRING,
    bid_strategy STRING,
    af_bid_strategy STRING,
    bid_amount STRING,
    original_bid_amount STRING,
    cost FLOAT64,
    impressions INT64,
    clicks INT64,
    installs INT64,
    re_attributions INT64,
    re_engagements INT64,
    original_cost FLOAT64,
    reported_impressions INT64,
    reported_clicks INT64,
    reported_conversions INT64,
    ctr FLOAT64,
    cvr FLOAT64,
    ecpm FLOAT64,
    cpi FLOAT64,
    ccvr FLOAT64,
    cvvr FLOAT64,
    reported_cvr FLOAT64,
    install_diff INT64,
    click_diff INT64,
    impression_diff INT64,
    ecpc FLOAT64,
    video_25p_views INT64,
    video_50p_views INT64,
    video_75p_views INT64,
    video_completions INT64,
    cost_without_fees FLOAT64,
    original_cost_without_fees FLOAT64,
    partition_field DATE,
    cluster_field INT64
)
PARTITION BY partition_field
CLUSTER BY cluster_field
OPTIONS(
    labels=[("job_name", f"{job_name}"), ("task_name", f"loading_to_dwh_{event_name}")]
)
AS 
SELECT
    app_id,
    media_source,
    date,
    os,
    agency,
    campaign,
    campaign_id,
    adset,
    adset_id,
    ad,
    ad_id,
    channel,
    geo,
    site_id,
    keyword_id,
    keyword_term,
    timezone,
    ad_account,
    currency,
    original_currency,
    campaign_objective,
    cost_model,
    af_cost_model,
    bid_strategy,
    af_bid_strategy,
    bid_amount,
    original_bid_amount,
    cost,
    impressions,
    clicks,
    installs,
    re_attributions,
    re_engagements,
    original_cost,
    reported_impressions,
    reported_clicks,
    reported_conversions,
    ctr,
    cvr,
    ecpm,
    cpi,
    ccvr,
    cvvr,
    reported_cvr,
    install_diff,
    click_diff,
    impression_diff,
    ecpc,
    video_25p_views,
    video_50p_views,
    video_75p_views,
    video_completions,
    cost_without_fees,
    original_cost_without_fees,
    CAST(dt as DATE) as partition_field,
    cast(b as INT64) as cluster_field
from `{lake_project_id}.appsflyer.v1`
WHERE partition_2 = '{event}';